apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafbat
  template:
    metadata:
      labels:
        app: kafbat
    spec:
      containers:
        - name: kafbat-ui
          image: kafbat/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9093"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080