apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi:latest
          ports:
            - containerPort: 8443
          env:
            - name: NIFI_WEB_HTTP_ENABLED
              value: "true"
            - name: NIFI_WEB_HTTPS_ENABLED
              value: "false"
            - name: NIFI_REMOTE_INPUT_SECURE
              value: "false"
            - name: NIFI_WEB_HTTP_PORT
              value: "8080"
            - name: NIFI_WEB_HTTPS_PORT
              value: "8443"
            - name: NIFI_WEB_HTTP_HOST
              value: "0.0.0.0"
            - name: NIFI_WEB_HTTPS_HOST
              value: "0.0.0.0"
            - name: NIFI_CLUSTER_PROTOCOL_IS_SECURE
              value: "false"
            - name: SINGLE_USER_USERNAME
              value: "9c455368-9362-4914-8efe-a07184a09576"
            - name: SINGLE_USER_PASSWORD
              value: "BmKW2I3NQb3yyk/nr+BpWb33jkrJunmQ"